name: Deploy to Azure Web App using Publish Profile

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # 1. ソースコードをチェックアウト
    - name: Checkout repository
      uses: actions/checkout@v3

    # 2. Azure Web App にデプロイ（Oryx ビルドを使用）
    - name: Deploy to Azure Web App (Oryx build)
      uses: azure/webapps-deploy@v2
      with:
        app-name: hosaka-rag-faq-web-app               # Azure Web App の名前
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }} # 発行プロファイル
        package: .                                     # デプロイ対象のパッケージ（リポジトリ全体）
